#!/bin/sh

if [ ! -e chosen_board.mk ]; then
	./configure BananaPi
fi
if [ -z "${CROSS_COMPILE}" ]; then
	CROSS_COMPILE=armv7l-unknown-linux-gnueabihf-
fi
CC=${CROSS_COMPILE}gcc
CXX=${CROSS_COMPILE}g++
if [ ! -z "$(which ccache)" ]; then
	CC="ccache ${CC}"
	CXX="ccache ${CXX}"
fi

make CROSS_COMPILE="${CROSS_COMPILE}" CC="${CC}" CXX="${CXX}" $*

