#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/tv/tvheadend-git/tvheadend-git.tar.gz"

function GetSourcePatch {
	sed -i "s/_gitname='tvheadend'/_gitname='tvheadend-git'/g" PKGBUILD
	sed -i "s/arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'armv7h')/g" PKGBUILD
	sed -i "s/depends=('avahi' 'openssl' 'python2')/depends=('avahi' 'openssl' 'python2' 'uriparser' 'libiconv' 'ffmpeg')/g" PKGBUILD
	sed -i "s/source=(\"git+https:\/\/github.com\/tvheadend\/tvheadend.git\"/source=(\"\${_gitname}::git+https:\/\/github.com\/tvheadend\/tvheadend.git\"/g" PKGBUILD
}
