#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/ap/apache-tools/apache-tools.tar.gz"

function GetSourcePatch {
	if [ -z "$(grep "arch=(i686 x86_64 armv7h)" PKGBUILD)" ]; then
		sed -i "s/arch=(i686 x86_64)/arch=(i686 x86_64 armv7h)/g" PKGBUILD
	fi
}

