#!/bin/sh

SOURCETYPE="ABS"
SOURCEPATH="/var/abs/extra/nginx/"

function GetSourcePatch {
	sed -i "s/^pkgdesc='Lightweight HTTP server and IMAP\/POP3 proxy server'$/pkgdesc='Lightweight HTTP server and IMAP\/POP3 proxy server with WebDAV missing methods support'/g" PKGBUILD
	sed -i "s/^arch=('i686' 'x86_64')$/arch=('i686' 'x86_64' 'armv7h')/g" PKGBUILD
	sed -i "s/^makedepends=('hardening-wrapper')$/#makedepends=('hardening-wrapper')/g" PKGBUILD
	sed -i "s/^source=(\(.*\)$/source=(\1\n\
        https:\/\/github.com\/arut\/nginx-dav-ext-module\/archive\/master.zip/g" PKGBUILD
	sed -i "s/^md5sums=(\(.*\)$/md5sums=(\1\n\
         'SKIP'/g" PKGBUILD
	sed -i "s/--with-http_sub_module/--with-http_sub_module\n\
    --add-module=\${srcdir}\/nginx-dav-ext-module-master/g" PKGBUILD
	sed -i "s/--with-http_sub_module/--with-http_sub_module \\\/g" PKGBUILD
}

