post_install() {
	if [ -e /usr/share/xsessions/kodi.desktop ] && [ -e /usr/share/xsessions/xbmc.desktop ]; then
		rm -rf /usr/share/xsessions/xbmc.desktop
	fi
}

pre_upgrade() {
	post_remove
}

post_upgrade() {
	post_install
}

post_remove() {
	if [ -e /usr/share/xsessions/kodi.desktop ] && [ ! -e /usr/share/xsessions/xbmc.desktop ]; then
		pushd . &> /dev/null
		cd /usr/share/xsessions
		ln -s kodi.desktop xbmc.desktop
		popd &> /dev/null
	fi
}
