#!/bin/bash

if [ -z "$1" ]; then
	#wget -qN -P /harddisk/UTIL http://test4.me/mc/xmltv.xml
	#cat /harddisk/UTIL/xmltv.xml
	curl -s -f http://test4.me/mc/xmltv.xml | sed -e "/<display-name>5 SBS<\/display-name>/d" -e "/<display-name>5<\/display-name>/d" -e "s/I5.6.microsoft.com/I5.5.microsoft.com/g" -e "/<display-name>7 KBS2<\/display-name>/d" -e "/<display-name>7<\/display-name>/d" -e "/<display-name>9 KBS1<\/display-name>/d" -e "/<display-name>9<\/display-name>/d"  -e "/<display-name>11 SEOULMBC<\/display-name>/d" -e "/<display-name>11<\/display-name>/d" -e "s/SEOULMBC/MBC/g"  -e "/<display-name>13 EBS_2<\/display-name>/d" -e "/<display-name>13<\/display-name>/d" -e "s/EBS_2/EBS/g"
	exit 0
fi

case "$1" in
	--description)
	echo "EPG grabber"
	;;

	--version)
	echo "1.0"
	;;

	--capabilities)
	echo "baseline"
	;;
esac
